### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by patrys666** [PrestaShop/ps_productinfo#1]
Hello, how to change position of Product tooltips?

**Comment by aleeks** [comment]
Hello @patrys666 
I think, you can add to your css style for `.js-productinfo`.
I think the best choice is to override the template in your theme, add an id & theme it.
With the classic theme, they are top-right on your page, i think with position absolute.

**Comment by patrys666** [comment]
Hi @aleeks, thank for your reply.  
I have one more problem with installing this module because presta says: This file does not seem to be a valid module zip

**Comment by aleeks** [comment]
wow, you didn't have the module installed by default ?

**Comment by patrys666** [comment]
Nevermind, It works now, sorry for wasting your time ;)

**Comment by aleeks** [comment]
No problem :)
